export const ACTION_TYPES = {
  FETCH_START: "FETCH_START",
  FETCH_SUCCESS: "FETCH_SUCCESS",
  FETCH_ERROR: "FETCH_ERROR",
  SET_SELECTED_DATA: "SET_SELECTED_DATA",
  DELETE_POST: "DELETE_POST",
  RESET_FORM: "RESET_FORM",
  UPDATE_SELECTED_POST: "UPDATE_SELECTED_POST",
  REMOVE_ERROR: "REMOVE_ERROR",
};
